version_2_with_negative: False
test:
    _target_: "context_compression.custom_datasets.llama_dataset_squad_custom.LlamaDatasetCustom"
    split: "test"
    data_config:
        prompt: "Please complete the code given"
        question_prompt: "What is the next line of code?"
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: "THUDM/LongBench"
        pad_to_max_length: False
        max_length: 128
        max_answer_length: 64
        dataset_config_name: "lcc"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64
        context_max_length: 40000
        use_rag: False
