version_2_with_negative: False
test:
    _target_: "generative_modeling.custom_datasets.llama_dataset_squad_custom.LlamaDatasetCustom"
    split: "test"
    data_config:
        prompt: "You are given 30 paragraphs from Wikipedia. Please determine which paragraph the abstract in the question field is from. Please enter the number of the paragraph that the abstract is from. The answer format must be like \"Paragraph 1\", \"Paragraph 2\", etc."
        question_prompt: null
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: "THUDM/LongBench"
        pad_to_max_length: False
        max_length: 10000
        max_answer_length: 32
        dataset_config_name: "passage_retrieval_en"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 512
        context_max_length: 18000
