version_2_with_negative: False
test:
    _target_: "generative_modeling.custom_datasets.llama_dataset_squad_custom.LlamaDatasetCustom"
    split: "test"
    data_config:
        prompt: "You are given a meeting transcript and a query containing a question or instruction. Answer the query in one or more sentences."
        question_prompt: null
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: "THUDM/LongBench"
        pad_to_max_length: False
        max_length: 10000
        max_answer_length: 512
        dataset_config_name: "qmsum"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64
        context_max_length: 35000
