version_2_with_negative: True
train:
    _target_: "context_compression.custom_datasets.seq2seq_dataset_squad.Seq2SeqModelingDataset"
    split: "train"
    data_config:
        question_column: "question"
        context_column: "context"
        answer_column: "answers"
        id_column: "id"
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: True
        max_length: 512
        max_answer_length: 30
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None

validation:
    _target_: "context_compression.custom_datasets.seq2seq_dataset_squad.Seq2SeqModelingDataset"
    split: "validation"
    data_config:
        question_column: "question"
        context_column: "context"
        answer_column: "answers"
        id_column: "id"
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: True
        max_length: 512
        max_answer_length: 30
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None

test:
    _target_: "context_compression.custom_datasets.seq2seq_dataset_squad.Seq2SeqModelingDataset"
    split: "validation"
    data_config:
        question_column: "question"
        context_column: "context"
        answer_column: "answers"
        id_column: "id"
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: True
        max_length: 512
        max_answer_length: 30
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None
