version_2_with_negative: True
train:
    _target_: "context_compression.custom_datasets.llama_dataset_squad_custom.LlamaDatasetCustom"
    split: "train"
    data_config:
        question_prompt: null
        prompt: "Answer the question based solely on the given context. If the provided context allows for an answer, provide a concise response; otherwise, return a single blank space ' '. No inferences, guesses, or explanations."
        question_column: "question"
        context_column: "context"
        answer_column: "answers"
        id_column: "id"
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: False
        max_length: 256
        max_answer_length: 32
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64
        context_max_length: 3808

validation:
    _target_: "context_compression.custom_datasets.llama_dataset_squad_custom.LlamaDatasetCustom"
    split: "validation"
    data_config:
        question_prompt: null
        prompt: "Answer the question based solely on the given context. If the provided context allows for an answer, provide a concise response; otherwise, return a single blank space ' '. No inferences, guesses, or explanations."
        question_column: "question"
        context_column: "context"
        answer_column: "answers"
        id_column: "id"
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: False
        max_length: 256
        max_answer_length: 32
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64
        context_max_length: 3808

test:
    _target_: "context_compression.custom_datasets.llama_dataset_squad_custom.LlamaDatasetCustom"
    split: "validation"
    data_config:
        question_prompt: null
        prompt: "Answer the question based solely on the given context. If the provided context allows for an answer, provide a concise response; otherwise, return a single blank space ' '. No inferences, guesses, or explanations."
        question_column: "question"
        context_column: "context"
        answer_column: "answers"
        id_column: "id"
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: False
        max_length: 256
        max_answer_length: 32
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64
        context_max_length: 3808
