version_2_with_negative: True
train:
    _target_: "context_compression.custom_datasets.qa_dataset.QADataset"
    split: "train"
    data_config:
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: True
        doc_stride: 128
        max_length: 512
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None

validation:
    _target_: "context_compression.custom_datasets.qa_dataset.QADataset"
    split: "validation"
    data_config:
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: True
        doc_stride: 128
        max_length: 512
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None

test:
    _target_: "context_compression.custom_datasets.qa_dataset.QADataset"
    split: "validation"
    data_config:
        use_fp16: False
        dataset_name: "squad_v2"
        pad_to_max_length: True
        doc_stride: 128
        max_length: 512
        dataset_config_name: "squad_v2"
        train_file: None
        validation_file: None
        test_file: None
