version_2_with_negative: False
test:
    _target_: "context_compression.custom_datasets.llama_dataset_squad_custom.LlamaDatasetCustom"
    split: "test"
    data_config:
        prompt: "Given some examples of questions. Please determine the type of the question below."
        question_prompt: null
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: "THUDM/LongBench"
        pad_to_max_length: False
        max_length: 10000
        max_answer_length: 64
        dataset_config_name: "trec"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64
        context_max_length: 15000
