_target_: "transformers.AutoModelForQuestionAnswering.from_pretrained"
config:
    _target_: "transformers.AutoConfig.from_pretrained"
    pretrained_model_name_or_path: None
    trust_remote_code: True
trust_remote_code: True
