# @package _global_
defaults:
  - override /custom_datasets: repobench_custom
  - override /models: quantized_causal_llama_compress_model
  - override /tokenizers: causal_auto_tokenizer
  - override /trainers: trainer
  - override /predictors: qa_lm_predictor


models:
  pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"
  mode: "attention_score"
  split_size: 512
  target_token: 3000
  condition: "question"
  normalize: True
  distance_metric: None
  config:
    pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"

tokenizers:
  pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"

predictors:
  predictor_config:
    metric_name: "code_sim_score"
    task_type: "CLM"
    batch_size: ${trainers.evaluation_config.per_device_eval_batch_size}


trainers:
  mode: "eval"
  evaluation_config:
    with_tracking: True
    output_dir: ${oc.env:LOGS_ROOT}/llama_target${models.target_token}_chunksize${models.split_size}
    per_device_eval_batch_size: 1
    resume_from_checkpoint: False
    zero_shot: True

  logging_config:
    project_name: "repobench"
    name: ${trainers.evaluation_config.output_dir}
