_target_: "context_compression.trainers.trainer.Trainer"
mode: "train"
training_config:
  seed: 0 # A seed for reproducible training.
  with_tracking: True # Whether to enable experiment trackers for logging.
  report_to: "wandb" # "tensorboard", "wandb", "comet_ml" and "clearml". Use "all" to report to all integrations. Only applicable when `--with_tracking` is passed."
  resume_from_checkpoint: False # If the training should continue from a checkpoint folder.
  per_device_train_batch_size: 4 # Batch size (per device) for the training dataloader.
  per_device_val_batch_size: 4 # Batch size (per device) for the evaluation dataloader.
  total_steps: 10000 # Total number of training steps to perform. If provided, overrides num_epochs.
  num_epochs: None # Total number of training epochs to perform.
  checkpointing_steps: "2000" # Whether the various states should be saved at the end of every n steps, or epoch for each epoch.
  gradient_accumulation_steps: 1 # Number of updates steps to accumulate before performing a backward/update pass.
  push_to_hub: False # Regardless of whether to push the model to the Hub.
  output_dir: ${oc.env:LOGS_ROOT}/exp_run_fine_tuning
  hub_model_id: "" # The name of the repository to keep in sync with the local output_dir.
  hub_token: "" # The token to use to push to the Model Hub.


optimization_config:
    learning_rate: 1e-5
    weight_decay: 0.03 # Weight decay to use.
    scheduler_name: "cosine" # The scheduler type to use. "linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"
    num_warmup_steps: 1000 # Number of steps for the warmup in the lr scheduler.

optimizer:
  _target_: "torch.optim.AdamW"
  params: None
  lr: ${trainers.optimization_config.learning_rate}

evaluation_config:
  seed: 1
  with_tracking: True
  report_to: "wandb"
  output_dir: ${oc.env:LOGS_ROOT}/eval_run_fine_tuning
  per_device_eval_batch_size: 4
  resume_from_checkpoint: True
  zero_shot: False

logging_config:
  project_name: "default_project"
  entity_name: "testwandb1"
  name: "default_name"
