# @package _global_
defaults:
  - override /custom_datasets: multinews_custom
  - override /models: quantized_causal_compress_llmlingua_model
  - override /tokenizers: causal_auto_tokenizer
  - override /trainers: trainer
  - override /predictors: qa_lm_predictor


models:
  pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"
  split_size: 200
  target_token: 1000
  tokenizer_name: "meta-llama/Llama-2-7b-chat-hf"
  config:
    pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"

tokenizers:
  pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"

predictors:
  predictor_config:
    metric_name: "rouge"
    task_type: "CLM"
    batch_size: ${trainers.evaluation_config.per_device_eval_batch_size}


trainers:
  mode: "eval"
  evaluation_config:
    with_tracking: True
    output_dir: ${oc.env:LOGS_ROOT}/eval_zeroshot_multinews_llmlingua_target${models.target_token}_chunksize${models.split_size}_llama_7b-chat_reorderfix_fixedk
    per_device_eval_batch_size: 1
    resume_from_checkpoint: False
    zero_shot: True

  logging_config:
    project_name: "multinews"
    name: ${trainers.evaluation_config.output_dir}
