# @package _global_
defaults:
  - override /custom_datasets: hotpot_qa_custom
  - override /models: quantized_causal_compress_llmlingua_mistral_model
  - override /tokenizers: causal_auto_tokenizer
  - override /trainers: trainer
  - override /predictors: qa_lm_predictor


models:
  pretrained_model_name_or_path: "mistralai/Mistral-7B-Instruct-v0.2"
  split_size: 200
  target_token: 1000
  tokenizer_name: "mistralai/Mistral-7B-Instruct-v0.2"
  config:
    pretrained_model_name_or_path: "mistralai/Mistral-7B-Instruct-v0.2"

tokenizers:
  pretrained_model_name_or_path: "mistralai/Mistral-7B-Instruct-v0.2"

predictors:
  predictor_config:
    metric_name: "squad"
    task_type: "CLM"
    batch_size: ${trainers.evaluation_config.per_device_eval_batch_size}


trainers:
  mode: "eval"
  evaluation_config:
    with_tracking: True
    output_dir: ${oc.env:LOGS_ROOT}/mistral_llmlingua_target${models.target_token}
    per_device_eval_batch_size: 1
    resume_from_checkpoint: False
    zero_shot: True

  logging_config:
    project_name: "hotpotqa"
    name: ${trainers.evaluation_config.output_dir}
