# @package _global_
defaults:
  - override /custom_datasets: squad_v2_for_llama
  - override /models: quantized_causal_model
  - override /tokenizers: causal_auto_tokenizer
  - override /trainers: trainer
  - override /predictors: qa_lm_predictor


models:
  pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"
  config:
    pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"

tokenizers:
  pretrained_model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"

predictors:
  predictor_config:
    task_type: "CLM"
    batch_size: ${trainers.evaluation_config.per_device_eval_batch_size}


trainers:
  mode: "eval"
  evaluation_config:
    with_tracking: True
    output_dir: ${oc.env:LOGS_ROOT}/eval_zeroshot_squad_v2_qa_lm_vanilla_llama_7b-chat
    per_device_eval_batch_size: 8
    resume_from_checkpoint: False
    zero_shot: True

  logging_config:
    project_name: "qa_squad_v2"
    name: ${trainers.evaluation_config.output_dir}
